In [ ]:
import pandas as pd
df=pd.read_csv("./data/auto-mpg.csv",header=None)
df.columns = ['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model year', 'origin', 'car name']
df.head()
df.tail()

In [ ]:
#데이터요약정보확인하기
df.head(2)
df.shape #몇행 몇열
#데이터프레임의기본정보
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    str
 4   weight        398 non-null    float64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
 8   car name      398 non-null    str
dtypes: float64(4), int64(3), str(2)
memory usage: 28.1 KB

In [ ]:
df.dtypes
df["mpg"].dtype
#df["mpg"].dtypes 가능

dtype('float64')

In [ ]:
#기술 통계 정보 요약
df.describe() 
#count : 데이터 개수, mean : 평균, 
#std : 표준편차, 편차의제곱(마이너스,양수차이를없애기위해) 루트씌워준거 
#min : 최소값, 25% : 1사분위수, 50% : 2사분위수(중앙값), 
#75% : 3사분위수, max : 최대값

,mpg,cylinders,displacement,weight,acceleration,model year,origin
count,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,2970.424623,15.568090,76.010050,1.572864
std,7.815984,1.701004,104.269838,846.841774,2.757689,3.697627,0.802055
min,9.000000,3.000000,68.000000,1613.000000,8.000000,70.000000,1.000000
25%,17.500000,4.000000,104.250000,2223.750000,13.825000,73.000000,1.000000
50%,23.000000,4.000000,148.500000,2803.500000,15.500000,76.000000,1.000000
75%,29.000000,8.000000,262.000000,3608.000000,17.175000,79.000000,2.000000
max,46.600000,8.000000,455.000000,5140.000000,24.800000,82.000000,3.000000

In [18]:
df.describe(include='all') #모든 컬럼에 대한 기술 통계 정보 요약
#df.describe(include=[object]) #문자열 컬럼에 대한 기술 통계 정보 요약
df.describe(exclude=["number"]) #숫자형 컬럼을 제외한 기술 통계 정보 요약
#count = df.count() #각 컬럼별 데이터 개수
#unique = df.nunique() #각 컬럼별 고유값 개수
#top = df.mode() #각 컬럼별 최빈값
#freq = df.apply(pd.Series.value_counts) #각 컬럼별 고유값 빈도수

       horsepower    car name
count         398         398
unique         94         305
top         150.0  ford pinto
freq           22           6

In [19]:
#데이터개수확인
df.count()

mpg             398
cylinders       398
displacement    398
horsepower      398
weight          398
acceleration    398
model year      398
origin          398
car name        398
dtype: int64

In [24]:
type(df.count()) 
imsi =df.count()
imsi["origin"] #origin 컬럼의 데이터 개수 확인

np.int64(398)

In [23]:
df["origin"]
df["origin"].value_counts() #origin 컬럼의 고유값 개수 확인

origin
1    249
3     79
2     70
Name: count, dtype: int64

In [ ]:
df["origin"].value_counts(normalize=True) #origin 컬럼의 고유값 비율 확인

origin
1    0.625628
3    0.198492
2    0.175879
Name: proportion, dtype: float64

In [26]:
df["origin"].value_counts(normalize=True)*100

origin
1    62.562814
3    19.849246
2    17.587940
Name: proportion, dtype: float64

In [27]:
(df["origin"].value_counts(normalize=True)*100).round(1) #소수점 첫째자리까지 반올림

origin
1    62.6
3    19.8
2    17.6
Name: proportion, dtype: float64